#!/bin/sh
##
## NAUTILUS
## SCRIPT: 00_anyfile_LIST-HAL-DEVICES_lshal.sh
##
## PURPOSE: List HAL (Hardware Abstraction Layer) devices for this computer
##          --- using 'lshal'.
##
## METHOD:  Puts the output in a text file and shows the text file in
##          a text-viewer of the user's choice.
##
## HOW TO USE: In Nautilus, select ANY file in ANY directory.
##             Then right-click and choose this script to run (name above).
##
#############################################################################
## Script
## Created: 2010may12
## Changed: 2011may02 Added $USER to a temp filename.
## Changed: 2011may11 Get 'nautilus-scripts' directory via an include script.
## Changed: 2012apr18 Changed script name in comments above and touched up
##                    the comments. Changed some indenting below.
#######################################################################

## FOR TESTING: (show statements as they execute)
#  set -x

##################################################################
## Prep a temporary filename, to hold the list of filenames.
##      We put the outlist file in /tmp, in case the user
##      does not have write-permission in the current directory,
##      and because the output does not, usually, have anything
##      to do with the current directory.
##################################################################

OUTLIST="/tmp/${USER}_list_HAL_devices.lis"
 
if test -f "$OUTLIST"
then
   rm -f "$OUTLIST"
fi


#################################
## Make the HEADER for the list.
#################################

THISHOST=`hostname`

echo "\
................ `date '+%Y %b %d  %a  %T%p %Z'` ......................

HAL (Hardware Abstraction Layer) devices
--- for host:  $THISHOST


Some more information is at the bottom of this list.

------------------------------------------------------------------------------
" > "$OUTLIST"


#################################################
## Use 'lshal' to make the main part of the list.
#################################################

EXECHECK=`which lshal`

if test -f "$EXECHECK"
then
    echo "
#####
lshal :
#####
" >> $OUTLIST
    lshal >> "$OUTLIST"
fi


##################################
## Make the TRAILER for the list.
##################################

SCRIPT_BASENAME=`basename $0`
SCRIPT_DIRNAME=`dirname $0`

echo "
................ `date '+%Y %b %d  %a  %T%p %Z'` ......................

  The list above was generated by the script

$SCRIPT_BASENAME

  in directory

$SCRIPT_DIRNAME


  If you want to add more HAL device info via more commands,
  you can simply edit the script.

------------------------------------------------------------------------------
FOR MORE INFO ON THESE EXECUTABLES:

For some of these topics (or commands like 'lshal'),
you can type 'man <topic-name>' to see details on the topic.
    ('man' stands for Manual.  It gives you a user manual 
     for a command/utility/protocol/topic.)

You can type 'man man' at a shell prompt to see a description of
the 'man' command.

Or use the 'show_manhelp_4topic' Nautilus script in the
'LinuxHELPS' group of Nautilus scripts.


******* END OF LIST of hardware info on host $THISHOST *******
" >> "$OUTLIST"


###########################
## Show the listing.
###########################

## . $HOME/.gnome2/nautilus-scripts/.set_VIEWERvars.shi

. $HOME/.freedomenv/feNautilusScripts/set_DIR_NautilusScripts.shi
. $DIR_NautilusScripts/.set_VIEWERvars.shi

$TXTVIEWER  "$OUTLIST"
