#!/bin/sh
##
## Nautilus
## SCRIPT: D0_anyfile4Dir_LIST_DIRS-all_allLEVS_find-d.sh
##
## PURPOSE: Lists ALL directories under a directory (including the
##          'hidden' directories), using the 'find' command.
##
## METHOD:  Puts the output of the 'find' command in a text file.
##
##          Shows the text file in a text-file viewer of the user's
##          choice.
##
## HOW TO USE: In Nautilus, select any file in the desired directory.
##             Then right-click and choose this Nautilus script to run.
##
## Created: 2011apr25
## Changed: 2011may11 Get 'nautilus-scripts' directory via an include script.
## Changed: 2011may22 Changed the wording in the header of the list.
## Changed: 2012feb29 Changed the script name in the comment above.

## FOR TESTING: (show statements as they execute)
# set -x

##############################################
## Prepare the output file.
##
## If the user has write-permission on the
## current directory, put the file in the pwd.
## Otherwise, put the file in /tmp.
##############################################

CURDIR="`pwd`"

OUTFILE="${USER}_temp_dirsLIST_recursive.txt"

if test ! -w "$CURDIR"
then
   OUTFILE="/tmp/$OUTFILE"
fi

if test -f "$OUTFILE"
then
   rm -f "$OUTFILE"
fi


#####################################
## Generate a heading for the listing.
#####################################

DATETIME=`date '+%Y %b %d  %a  %T%p'`

echo "\
..................... $DATETIME ............................

List of  DIRECTORIES-ONLY  under the directory
  $CURDIR
--- ALL levels.

...........................................................................
" >  "$OUTFILE"


#######################################
## Add the 'find' output to the listing.
#######################################

find . -type d -name '*' -print |  sort >> "$OUTFILE"


#####################################
## Add a trailer to the listing.
#####################################

SCRIPT_BASENAME=`basename $0`
SCRIPT_DIRNAME=`dirname $0`

echo "
...........................................................................

This list was generated by script
   $SCRIPT_BASENAME
in directory
   $SCRIPT_DIRNAME

Used command
     find . -type d -name '*' -print |  sort

..................... $DATETIME ............................
" >>  "$OUTFILE"


#######################
## Show the list.
#######################

## . $HOME/.gnome2/nautilus-scripts/.set_VIEWERvars.shi

. $HOME/.freedomenv/feNautilusScripts/set_DIR_NautilusScripts.shi
. $DIR_NautilusScripts/.set_VIEWERvars.shi

$TXTVIEWER "$OUTFILE" &
