#!/bin/sh
##
## Nautilus
## SCRIPT: 00_LIST_X-COLORS_showrgb.sh
##
## PURPOSE: List the X color names and RGB values, via 'showrdb'.
##
## METHOD:  Puts the output of 'showrgb' in a text file.
##
##          This script shows the text file using a textfile-viewer of
##          the user's choice.
##
## HOW TO USE: In Nautilus, select ANY file in ANY directory.
##             Then right-click and choose this script to run (name above).
##
############################################################################
## Created: 2010may30
## Changed: 2011may02 Added $USER to a temp filename.
## Changed: 2011may11 Get 'nautilus-scripts' directory via an include script.
## Changed: 2012may12 Changed script name in comments above and touched up
##                    the comments. Changed some indenting below.
#######################################################################

## FOR TESTING: (show statements as they execute)
#  set -x

################################################################
## Prep a temporary filename, to hold the list of color names.
##
##      We put the outlist file in /tmp, in case the user
##      does not have write-permission in the current directory,
##      and because the output does not, usually, have anything
##      to do with the current directory.
################################################################

OUTLIST="${USER}_list_Xcolors_showrgb.lis"

OUTLIST="/tmp/$OUTLIST"
 
if test -f "$OUTLIST"
then
   rm -f "$OUTLIST"
fi


##################################
## Make a HEADER for the list.
##################################

THISHOST=`hostname`

echo "\
................ `date '+%Y %b %d  %a  %T%p %Z'` ......................

X color names and their RGB values

--- for host:  $THISHOST


Some more information is at the bottom of this list.

------------------------------------------------------------------------------
" > "$OUTLIST"


##################################
## Make the list with 'showrgb'.
##################################

EXECHECK=`which showrgb`

if test -f "$EXECHECK"
then

   echo "
#######
showrgb output :
#######
" >> "$OUTLIST"

   showrgb | egrep -i -v 'grey' | sort | uniq  >> "$OUTLIST"

#       awk '{printf ("%-30s %3s %3s %3s\n", $1 $2 $3 $NF) }' | sort | uniq >> "$OUTLIST"

else  
   echo "
The program 'showrgb' does not seem to be available.
" >> "$OUTLIST"
fi


##################################
## Make a TRAILER for the list.
##################################

SCRIPT_DIRNAME=`dirname $0`
SCRIPT_BASENAME=`basename $0`

echo "
------------------------------------------------------------------------------

  The list above was generated by the script

$SCRIPT_BASENAME

  in directory

$SCRIPT_DIRNAME

  using 'showrgb', 'grep', 'sort', and 'uniq'.

  If you want to change the presentation format or the sort,
  you can simply edit the script.

------------------------------------------------------------------------------
FOR MORE INFO:

For more info the executables used,
you can type 'man <exe-name>' to see details on how the program
can be used.  ('man' stands for Manual.  It gives you the user
manual for the command/utility.)

You can type 'man man' at a shell prompt to see a description of
the 'man' command.

Or use the 'show_manhelp_4topic' Nautilus script in the
'LinuxHELPS' group of Nautilus scripts.


******* END OF LIST of X color names info, on host $THISHOST *******
" >> "$OUTLIST"


###################################
## Show the listing.
###################################

## . $HOME/.gnome2/nautilus-scripts/.set_VIEWERvars.shi

. $HOME/.freedomenv/feNautilusScripts/set_DIR_NautilusScripts.shi
. $DIR_NautilusScripts/.set_VIEWERvars.shi

$TXTVIEWER  "$OUTLIST"
