#!/bin/sh
##
## NAUTILUS
## SCRIPT: 03a_anyfile_LIST-Xft_FONTNAMES_fc-list.sh
##
## PURPOSE: List fontnames --- using 'fc-list'.
##
## METHOD:  Shows the list file in a text-viewer of the user's choice.
##
## HOW TO USE: In Nautilus, select ANY file in ANY directory.
##             Then right-click and choose this script to run (name above).
##
############################################################################
## Script
## Created: 2010may30
## Changed: 2010aug26 Added 'fc-list : family' output to the top of the list.
## Changed: 2011may02 Added $USER to a temp filename.
## Changed: 2011may11 Get 'nautilus-scripts' directory via an include script.
## Changed: 2012apr18 Changed script name in comments above and touched up
##                    the comments. Changed some indenting below.
#######################################################################

## FOR TESTING: (show statements as they execute)
#  set -x

###############################################################
## Prep a temporary filename, to hold the list of filenames.
##      We put the outlist file in /tmp, in case the user
##      does not have write-permission in the current directory,
##      and because the output does not, usually, have anything
##      to do with the current directory.
###############################################################

OUTLIST="${USER}_list_fonts_fc-list.lis"

OUTLIST="/tmp/$OUTLIST"
 
if test -f "$OUTLIST"
then
   rm -f "$OUTLIST"
fi


####################################
## Make the header for the list.
####################################

THISHOST=`hostname`

echo "\
................ `date '+%Y %b %d  %a  %T%p %Z'` ......................

fonts known to 'fc-list'
--- for host:  $THISHOST


Some more information is at the bottom of this list.

------------------------------------------------------------------------------
" > "$OUTLIST"


####################################
## Use 'fc-list' to make the list.
####################################

EXECHECK=`which fc-list`

if test -f "$EXECHECK"
then

   echo "
###########################
Command: 'fc-list : family'
###########################
" >> "$OUTLIST"

   fc-list : family | sort >> $OUTLIST

   echo "
###########################
Command: 'fc-list'
###########################
" >> "$OUTLIST"

   fc-list | sort >> "$OUTLIST"

else

   echo "
The command 'fc-list' does not seem to be available.
" >> "$OUTLIST"

fi


####################################
## Add a trailer to the list.
####################################

SCRIPT_DIRNAME=`dirname $0`
SCRIPT_BASENAME=`basename $0`

echo "
................ `date '+%Y %b %d  %a  %T%p %Z'` ......................

  The list above was generated by the script

$SCRIPT_BASENAME

  in the directory

$SCRIPT_DIRNAME

  If you want to change the presentation or add more font info,
  you can simply edit the script to change or enhance it.

------------------------------------------------------------------------------
FOR MORE INFO ON THESE EXECUTABLES:

For help on a topic, such as the command 'fc-list',
you can type 'man <topic-name>' to see details on the topic.
    ('man' stands for Manual.  It gives you a user manual 
     for a topic: command or utility or protocol or subsystem.)

You can type 'man man' at a shell prompt to see a description of
the 'man' command.

Or use the 'show_manhelp_4topic' Nautilus script in the
'LinuxHELPS' group of Nautilus scripts.


**** END OF LIST of fonts known to 'fc-list' on host $THISHOST ****
" >> "$OUTLIST"


##################################
## Show the listing.
##################################

## . $HOME/.gnome2/nautilus-scripts/.set_VIEWERvars.shi

. $HOME/.freedomenv/feNautilusScripts/set_DIR_NautilusScripts.shi
. $DIR_NautilusScripts/.set_VIEWERvars.shi

$TXTVIEWER "$OUTLIST"
