#!/bin/sh
##
## Nautilus
## SCRIPT: 00_anyfile_SHOW_MONITOR-DPI_xdpyinfo-xrdb.sh
##
## PURPOSE: Shows the DPI of the user's monitor --- two different ways
##          --- via 'xdpyinfo' and via 'xrdb'.
##
## Reference: bottom of the web page
##            https://wiki.archlinux.org/index.php/Font_Configuration
##
## METHOD: Puts the output in a text file and shows the text file
##         using a textfile-viewer of the user's choice.
##
## HOW TO USE: In Nautilus, select ANY file in ANY directory.
##             Then right-click and choose this script to run (name above).
##
#########################################################################
## Created: 2011jul14
## Changed: 2012may12 Changed script name in comments above and touched up
##                    the comments. Changed some indenting below.
###########################################################################


## FOR TESTING: (show statements as they execute)
# set -x

###############################################################
## Prep a temporary filename, to hold the output of xdpyinfo and
## xrdb.
##      We put the outlist file in /tmp, in case the user
##      does not have write-permission in the current directory,
##      and because the output does not, usually, have anything
##      to do with the current directory.
###############################################################

OUTLIST="/tmp/${USER}_monitorDPI_xdpyinfo-xrdb.lis"
 
if test -f "$OUTLIST"
then
   rm -f "$OUTLIST"
fi


#######################################
## Prepare the HEADER for the list.
#######################################

THISHOST=`hostname`

echo "\
................ `date '+%Y %b %d  %a  %T%p %Z'` ......................

Monitor DPI (dots per inch) info (via 'xdpyinfo' and 'xrdb')
--- for host:  $THISHOST


See the discussion of this output, below the output of 'xdpyinfo' and 'xrdb'.

------------------------------------------------------------------------------
" > "$OUTLIST"


#####################################################
## Use 'xdpyinfo' to create the 1st part of the list.
#####################################################

EXECHECK=`which xdpyinfo`

if test -f "$EXECHECK"
then

   echo "
####################
xdpyinfo | grep dot :
####################
" >> $OUTLIST

   xdpyinfo | grep dot >> "$OUTLIST"
fi


#####################################################
## Use 'xrdb' to create the 2nd part of the list.
#####################################################

EXECHECK=`which xrdb`

if test -f "$EXECHECK"
then

   echo "
######################
xrdb -query | grep dpi :
######################
" >> $OUTLIST

   xrdb -query | grep dpi >> "$OUTLIST"
fi


###########################
## Add TRAILER to the list.
###########################

SCRIPT_BASENAME=`basename $0`
SCRIPT_DIRNAME=`dirname $0`

echo "
------------------------------------------------------------------------------

  The list above was generated by the script

$SCRIPT_BASENAME

  in directory

$SCRIPT_DIRNAME

  If you want to add more X windows info, you can simply edit the script.

------------------------------------------------------------------------------
DISCUSSION OF THIS OUTPUT:

    (from the 'Distorted Fonts' section at the bottom of web page
     https://wiki.archlinux.org/index.php/Font_Configuration )

96 DPI is not a standard. You should use your monitor's actual DPI
to get proper font rendering, especially when using subpixels.

If fonts are still unexpectedly large or small, poorly proportioned
or simply rendering poorly, fontconfig may be using the incorrect DPI.

Fontconfig should be able to detect DPI parameters as discovered by
the Xorg server. You can check the auto-discovered DPI with xdpyinfo:

$ xdpyinfo | grep dots

  resolution:    102x102 dots per inch

[To use the 'xdpyinfo' command, you may need to install the package
'xorg-xdpyinfo'.]

If the DPI is detected incorrectly (usually due to an incorrect
monitor EDID), you can specify it manually in the Xorg configuration,
see https://wiki.archlinux.org/index.php/Xorg#Display_Size_and_DPI.

This is the recommended solution, but it may not work with buggy drivers.

Fontconfig will default to the Xft.dpi variable if it is set.
Xft.dpi is usually set by desktop environments (usually to
Xorg's DPI setting) or manually in ~/.Xdefaults or ~/.Xresources.

Use xrdb to query for the value:

$ xrdb -query | grep dpi

Xft.dpi:	102

Those still having problems can fall back to manually settin
the DPI used by fontconfig:

...
<match target=\"pattern\">
   <edit name=\"dpi\" mode=\"assign\"><double>96</double></edit>
</match>
...

[in file ~/.fonts.conf or /etc/fonts/local.conf.]

******* END OF DPI info for the monitor *******
" >> "$OUTLIST"


####################################
## Show the listing.
###################################

## . $HOME/.gnome2/nautilus-scripts/.set_VIEWERvars.shi

. $HOME/.freedomenv/feNautilusScripts/set_DIR_NautilusScripts.shi
. $DIR_NautilusScripts/.set_VIEWERvars.shi

$TXTVIEWER  "$OUTLIST"
